name: Publish helm chart
run-name: Publish helm chart

on:
  push:
    tags: ["chart-*"]
    branches: ['main', 'devel']
    paths: ['chart/**']

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository_owner }}/helm
  CHART_PATH: chart
  UPDATE_DEPS: 'false'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Extract metadata (chart name, tag)
        id: meta
        run: |
          echo "name=$(helm show chart ${{ env.CHART_PATH }} | grep 'name:' | awk '{print $2}')" >> "$GITHUB_OUTPUT"
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=$(echo '${{ github.ref_name }}' | awk -F '-' '{print $2}')" >> "$GITHUB_OUTPUT"
          else
            echo "tag=0.0.0-${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name:  Build and push Helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: ${{ steps.meta.outputs.name }}
          repository: ${{ env.REPO_NAME }}
          tag: ${{ steps.meta.outputs.tag }}
          path: ${{ env.CHART_PATH }}
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: '${{ env.UPDATE_DEPS }}'
