name: Publish helm chart
run-name: Publish helm chart

on:
  push:
    tags: ["chart-*"]
    branches: ['main', 'devel']
    paths: ['chart/**']

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository_owner }}/helm

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Extract metadata (chart name, tag)
        id: meta
        run: |
          echo "name=sandbox" >> "$GITHUB_OUTPUT"
          echo "tag=0.1.1" >> "$GITHUB_OUTPUT"

      - name:  Build and push Helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: ${{ steps.meta.outputs.name }}
          repository: ${{ env.REPO_NAME }}
          tag: ${{ steps.meta.outputs.tag }}
          path: chart
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'false'
